// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWP7L50N1XFccSRvgSBgsT3BoIsBSqt1Y',
    appId: '1:854170092423:web:799ff35bdfa2b94b568922',
    messagingSenderId: '854170092423',
    projectId: 'nowait-48142',
    authDomain: 'nowait-48142.firebaseapp.com',
    storageBucket: 'nowait-48142.appspot.com',
    measurementId: 'G-CP9ENY3FC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJoW1FlhRFjzOZd8PV_G4o9uIXLlek5Q',
    appId: '1:854170092423:android:f21d451f431d101c568922',
    messagingSenderId: '854170092423',
    projectId: 'nowait-48142',
    storageBucket: 'nowait-48142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtyd8aBhMRCSk7ewkupTGzOQZtw9nVY0',
    appId: '1:854170092423:ios:0c2902536e9b09a7568922',
    messagingSenderId: '854170092423',
    projectId: 'nowait-48142',
    storageBucket: 'nowait-48142.appspot.com',
    iosBundleId: 'com.example.noWait',
  );
}
